# Курс "Программирование на Python"


# Тема 7. Библиотека numpy

**NumPy** (Numerical Python) — это [библиотека Python](https://numpy.org/doc/stable/reference/index.html), предоставляющая возможность эффективной работы с многомерными массивами (ndarray), содержащая в себе широкий набор математических функций и инструментов для разлчиных вычислений.

In [3]:
import numpy as np

Создадим список из 100 случайных значений.

In [15]:
import random

# Генерация списка из 30 случайных целых чисел от 0 до 1000
random_numbers = [random.randint(0, 1000) for _ in range(30)]

print(random_numbers)

[836, 574, 439, 302, 705, 81, 349, 374, 684, 25, 49, 297, 122, 179, 637, 140, 305, 279, 946, 38, 477, 174, 918, 342, 2, 654, 795, 979, 723, 290]


Основным объектом numpy является `Ndarray` – это n-мерный массив (сокращение от n-dimensional array), структура данных, которая позволяет хранить набор элементов одного типа. Массивы могут быть одномерными, то есть визуально ничем не отличаться от простого списка значений.

Преимущества работы с массивами:
- Занимают меньше места и памяти. 
- Операции над массивами выполняются поэлементно: для выполнения действий над каждым элементом массива не нужно использовать какие-то специальные конструкции вроде циклов, можно обращаться сразу ко всему массиву.

In [16]:
np_numbers = np.array(random_numbers) # преобразуем список в массив
np_numbers

array([836, 574, 439, 302, 705,  81, 349, 374, 684,  25,  49, 297, 122,
       179, 637, 140, 305, 279, 946,  38, 477, 174, 918, 342,   2, 654,
       795, 979, 723, 290])

In [17]:
type(np_numbers)

numpy.ndarray

Можно обратиться к элементу массива по индексу.

In [18]:
np_numbers[3]

302

Можно сделать срез.

In [19]:
np_numbers[1:6]

array([574, 439, 302, 705,  81])

Можно изменить элемент.

In [20]:
np_numbers[3] = 12
np_numbers

array([836, 574, 439,  12, 705,  81, 349, 374, 684,  25,  49, 297, 122,
       179, 637, 140, 305, 279, 946,  38, 477, 174, 918, 342,   2, 654,
       795, 979, 723, 290])

Узнать число элементов массива.

In [21]:
len(np_numbers)

30

In [22]:
np_numbers.size

30

Содать копию массива.

In [23]:
np_numbers_copy = np_numbers.copy()
np_numbers_copy

array([836, 574, 439,  12, 705,  81, 349, 374, 684,  25,  49, 297, 122,
       179, 637, 140, 305, 279, 946,  38, 477, 174, 918, 342,   2, 654,
       795, 979, 723, 290])

Осуществить арифметические операции над элементами массива.

In [24]:
np_squares = np_numbers * 2  # удвоим элементы
np_squares

array([1672, 1148,  878,   24, 1410,  162,  698,  748, 1368,   50,   98,
        594,  244,  358, 1274,  280,  610,  558, 1892,   76,  954,  348,
       1836,  684,    4, 1308, 1590, 1958, 1446,  580])

Сложить два массива.

In [25]:
na1 = np.array([4, 5, 8, 9])
na2 = np.array([2, 3, 6, 10])
na1 + na2
# арифметические операции над массивами выполняются поэлементно

array([ 6,  8, 14, 19])

Перемножить два массива.

In [26]:
na1 * na2 

array([ 8, 15, 48, 90])

Применить функцию к массиву.

In [27]:
x = np.array([1, 2, 3, 4, 5])
np.sqrt(x) # используем функцию sqrt из numpy

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [28]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

Объединить массивы в один.

In [29]:
np.concatenate([na1, na2])

array([ 4,  5,  8,  9,  2,  3,  6, 10])

In [30]:
q = np.array([14, 8, 14, 9])
w = np.array([1, 3, 4])
q + w  # если у массивов разная длина, то ничего не получится

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

В массивах могут храниться не только числа, но все элементы, лежащие в одном массиве, должны быть одного типа. Элементы разного типа автоматически приводятся к одному самому "сильному" типу (к тому, в который могут быть преобразованы остальные без ошибки).

In [31]:
mixed_array = np.array([1, True, 3, "Hello"])
print(mixed_array)
# числа 1, 3 превратились в строчки '1', '3'. 

['1' 'True' '3' 'Hello']


In [32]:
n_array = np.array([1, True, 3, 5.])
n_array
# все числа превратились в вещественные

array([1., 1., 3., 5.])

In [33]:
n_array = np.array([1, True, 3, 5.5], int)  # можно указать тип, в который нужно преобразовать
n_array

array([1, 1, 3, 5])

Тип данных в массиве

In [34]:
n_array.dtype

dtype('int64')

Cоздать новый массив на основе выбранных элементов существующего.

In [35]:
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
y = x[[1, 3, 4]]
y

array([2.2, 4.4, 5.5])

Cоздать новый массив на основе условия.

In [36]:
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
y = x[ x < 4 ]  # создать новый массив на основе элементов, которые меньше 4
y

array([1.1, 2.2, 3.3])

In [38]:
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 30.3, 45.3, 56.7])
y = x[ (x < 50) & (x > 3) ]  # можно использовать несколько условий
y

array([ 3.3,  4.4,  5.5, 30.3, 45.3])

Атрибуты массива.

In [39]:
# Одномерный массив
a = np.array([1, 2, 3, 4])
# Двумерный массив
b = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
print(a.ndim)   # число измерений
print(a.shape)  # форма
print(a.size)   # количество элементов
print(a.dtype)  # тип данных элементов

1
(4,)
4
int64


In [41]:
print(b.ndim)   # число измерений 
print(b.shape)  # форма
print(b.size)   # количество элементов
print(b.dtype)  # тип данных элементов

2
(2, 3)
6
int64


Статистичские показатели.

In [42]:
# массив с оценками школьников
marks = np.array([5, 2, 3, 5, 5, 4, 3, 4]) 
marks

array([5, 2, 3, 5, 5, 4, 3, 4])

In [43]:
print('Минимальная оценка:', marks.min())
print('Максимальная оценка:', marks.max())
print('Средняя оценка:', marks.mean())
print('Медиана:', np.median(marks))
print('Сумма:', np.sum(marks))
print('Стандартное отклонение:', np.std(marks))

Минимальная оценка: 2
Максимальная оценка: 5
Средняя оценка: 3.875
Медиана: 4.0
Сумма: 31
Стандартное отклонение: 1.0532687216470449


In [44]:
print('Индекс максимального значения:', marks.argmax())
# если таких значений несколько, то возвращается индекс первого встречающегося значения

Индекс максимального значения: 0


In [45]:
print('Индекс минимального значения:', marks.argmin())
# если таких значений несколько, то возвращается индекс первого встречающегося значения

Индекс минимального значения: 1


# Задание 1

Написать функцию `double_this(arr)`, принимающую на вход массив arr, состоящий из чисел, и возвращающую массив, полученный удвоением каждого элемента `arr`.

In [4]:
# здесь записать решение задания 1 ☆ﾟ.*･｡ﾟ
def double_this(arr):
    return arr * 2

In [5]:
def test_double_this():
    # Тест 1: Простой массив целых чисел
    arr1 = np.array([1, 2, 3])
    result1 = double_this(arr1)
    expected1 = np.array([2, 4, 6])
    assert np.array_equal(result1, expected1), f"Ожидалось {expected1}, получено {result1}"
    
    # Тест 2: Массив с отрицательными числами и нулем
    arr2 = np.array([-1, 0, 5])
    result2 = double_this(arr2)
    expected2 = np.array([-2, 0, 10])
    assert np.array_equal(result2, expected2), f"Ожидалось {expected2}, получено {result2}"
    
    # Тест 3: Массив дробных чисел
    arr3 = np.array([2.5, 1.5, 0.0])
    result3 = double_this(arr3)
    expected3 = np.array([5.0, 3.0, 0.0])
    assert np.allclose(result3, expected3), f"Ожидалось {expected3}, получено {result3}"
    
    # Тест 4: Пустой массив
    arr4 = np.array([])
    result4 = double_this(arr4)
    expected4 = np.array([])
    assert np.array_equal(result4, expected4), f"Ожидалось {expected4}, получено {result4}"
    
    # Тест 5: Одномерный массив с одним элементом
    arr5 = np.array([7])
    result5 = double_this(arr5)
    expected5 = np.array([14])
    assert np.array_equal(result5, expected5), f"Ожидалось {expected5}, получено {result5}"
    
    # Тест 6: Многомерный массив (матрица)
    arr6 = np.array([[1, 2], [3, 4]])
    result6 = double_this(arr6)
    expected6 = np.array([[2, 4], [6, 8]])
    assert np.array_equal(result6, expected6), f"Ожидалось {expected6}, получено {result6}"
    
    # Тест 7: Проверка, что исходный массив не изменяется
    arr7 = np.array([1, 2, 3])
    original = arr7.copy()
    result7 = double_this(arr7)
    assert np.array_equal(arr7, original), "Исходный массив был изменен!"
    
    # Тест 8: Массив с большими числами
    arr8 = np.array([1000000, 2000000])
    result8 = double_this(arr8)
    expected8 = np.array([2000000, 4000000])
    assert np.array_equal(result8, expected8), f"Ожидалось {expected8}, получено {result8}"
    
    print("Все тесты пройдены успешно!")

test_double_this()

Все тесты пройдены успешно!


# Задание 2
Написать функцию `select_even(arr)`, принимающую на вход массив целых чисел arr и возвращающую новый массив, который состоит из всех чётных элементов `arr`.

In [6]:
# здесь записать решение задания 2 ♡‧₊˚✧ ૮ ˶ᵔ ᵕ ᵔ˶ ა ✧˚₊‧♡
def select_even(arr):
    return arr[arr % 2 == 0]

In [7]:
def test_select_even():
    # Тест 1: Простой массив с четными и нечетными числами
    arr1 = np.array([1, 2, 3, 4, 5, 6])
    result1 = select_even(arr1)
    expected1 = np.array([2, 4, 6])
    assert np.array_equal(result1, expected1), f"Ожидалось {expected1}, получено {result1}"
    
    # Тест 2: Массив с отрицательными числами
    arr2 = np.array([-3, -2, -1, 0, 1, 2])
    result2 = select_even(arr2)
    expected2 = np.array([-2, 0, 2])
    assert np.array_equal(result2, expected2), f"Ожидалось {expected2}, получено {result2}"
    
    # Тест 3: Массив без четных чисел
    arr3 = np.array([1, 3, 5, 7])
    result3 = select_even(arr3)
    expected3 = np.array([])
    assert np.array_equal(result3, expected3), f"Ожидалось {expected3}, получено {result3}"
    
    # Тест 4: Пустой массив
    arr4 = np.array([])
    result4 = select_even(arr4)
    expected4 = np.array([])
    assert np.array_equal(result4, expected4), f"Ожидалось {expected4}, получено {result4}"
    
    # Тест 5: Многомерный массив
    arr5 = np.array([[1, 2, 3], [4, 5, 6]])
    result5 = select_even(arr5)
    expected5 = np.array([2, 4, 6])
    assert np.array_equal(result5, expected5), f"Ожидалось {expected5}, получено {result5}"
    
    # Тест 6: Проверка, что исходный массив не изменяется
    arr6 = np.array([1, 2, 3, 4])
    original = arr6.copy()
    result6 = select_even(arr6)
    assert np.array_equal(arr6, original), "Исходный массив был изменен!"
    
    # Тест 7: Большой массив
    arr7 = np.arange(100)  # числа от 0 до 99
    result7 = select_even(arr7)
    expected7 = np.arange(0, 100, 2)  # все четные числа от 0 до 98
    assert np.array_equal(result7, expected7), f"Ожидалось {expected7}, получено {result7}"
    
    print("Все тесты пройдены успешно!")

test_select_even()

Все тесты пройдены успешно!


# Задание 3

Есть данные о росте баскетболистов в дюймах (список `height_in`) и весе в фунтах (список `weight_lb`). Выполните следующее:
- Преобразуйте списки в массивы и далее работайте только с массивами.
- Переведите рост в метры, а вес в килограммы.
    - 1 дюйм = 0.0254 метра
    - 1 фунт = 0.4536 килограмма
- Рассчитайте индекс массы тела (ИМТ) для каждого баскетболиста. ИМТ = вес (в килограммах) / (рост (в метрах)) ** 2.
- Создайте новый массив, содержащий ИМТ из баскетболистов, у которых значение ИМТ < 21. Сколько таких спортсменов?

In [9]:
# рост баскетболистов в дюймах
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 
             74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 
             76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 
             75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 
             74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 
             72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 
             73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 
             72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 
             78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 
             73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 
             73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 
             77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 
             72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 
             72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 
             77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 
             76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 
             73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 
             72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 
             73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 
             74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 
             76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 
             76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 
             71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 
             75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 
             77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 
             73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 
             79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 
             76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 
             79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 
             72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 
             75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 
             75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 
             75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 
             74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 
             72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 
             75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 
             68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 
             74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 
             76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 
             74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 
             75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 
             71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 
             70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 
             74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 
             74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 
             76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 
             74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 
             73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 
             72, 75, 73, 74, 75, 75, 73]
# вес баскетболистов в фунтах
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189,
             185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 
             245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 
             200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 
             210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 
             235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 
             180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 
             230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 
             210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 
             185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 
             195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 
             180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 
             185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 
             225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 
             225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 
             215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 
             190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 
             190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 
             200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 
             175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 
             240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 
             150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 
             202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 
             190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 
             227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 
             200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 
             190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 
             185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 
             200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 
             210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 
             245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 
             190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 
             225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 
             210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 
             220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 
             220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 
             180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 
             190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 
             190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 
             200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 
             200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 
             180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 
             186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 
             185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190,
             210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 
             244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 
             183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 
             196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 
             195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 
             190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 
             185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 
             208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 
             205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235,
             210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 
             245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 
             212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 
             215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 
             208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 
             225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 
             230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

In [10]:
# здесь записать решение задания 3 ≽^•⩊•^≼ 
height_in_2 = np.array(height_in)
weight_lb_2 = np.array(weight_lb)
weight_lb_2  # 1

array([180, 215, 210, ..., 205, 190, 195])

In [11]:
height_in_2 = height_in_2 * 0.0254
weight_lb_2 = weight_lb_2 * 0.4536
weight_lb_2  # 2

array([81.648, 97.524, 95.256, ..., 92.988, 86.184, 88.452])

In [13]:
bmi = weight_lb_2  / ((height_in_2) ** 2)
bmi  # 3 

array([23.11078399, 27.60454754, 28.48130696, ..., 25.62341125,
       23.7485275 , 25.72731736])

In [14]:
low_bmi = bmi[bmi < 21]
print("ИМТ баскетболистов с ИМТ < 21:", low_bmi)
print(len(low_bmi))  # 4

ИМТ баскетболистов с ИМТ < 21: [20.5429191  20.5429191  20.69318543 20.69318543 20.34379069 20.34379069
 20.69318543 20.15919026 19.498791   20.69318543 20.92089088]
11


# Многомерные массивы

## Двумерный массив

In [47]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], 
                  [65.4, 59.2, 63.3, 88.4, 68.7]])
np_2d

# рост и вес спортсменов

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.3 , 88.4 , 68.7 ]])

In [48]:
np_2d.shape  # показывает число строк и столбцов в массиве

(2, 5)

In [49]:
np_2d[1]  # вторая строка

array([65.4, 59.2, 63.3, 88.4, 68.7])

In [50]:
np_2d[1][0]  # первый элемент второй строки

65.4

In [51]:
np_2d[:,1:3]  # все строки, второй и третий столбцы

array([[ 1.68,  1.71],
       [59.2 , 63.3 ]])

In [52]:
np.mean(np_2d[:,1:3])  # среднее арифметическое отобранных элементов

31.4725

Агрегирующие функции

In [53]:
print(np_2d.mean(axis=1))  # среднее по строкам

[ 1.76 69.  ]


## Трехмерный массив

Создадим массив с оценками 3-х учеников по 5-ти предметам.

In [56]:
grades = np.array([[3, 5, 5, 4, 3],
       [3, 3, 4, 3, 3],
       [5, 5, 5, 4, 5]])

In [57]:
grades.shape

(3, 5)

Поменяем местами строки и столбцы с помощью транспонирования.

In [58]:
grades.transpose() 

array([[3, 3, 5],
       [5, 3, 5],
       [5, 4, 5],
       [4, 3, 4],
       [3, 3, 5]])

# Задание 4

Дан список списков `baseball`, содержащий данные о росте и весе спортсменов. Выполните следующее:
1. Превратите список `baseball` в двумерный массив `np_baseball`.
2. На основе двумерного массива `np_baseball` сформируйте одномерный массив `np_weight`, содержащий только вес баскетболистов.
3. Измените единицы измерения показателей в двумерном массиве `np_baseball`, переведя сантиметры в метры, а килограммы в граммы.
4. Рассчитайте средний вес и медиану по росту.
5. Рассчитайте корреляцию между ростом и весом (`corrcoef`), напишите в комментарии какая корреляция наблюдается - сильная, средняя или слабая?

In [15]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
baseball

[[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]

In [16]:
# здесь записать решение задания 4 ✿˚ ༘ ⋆｡♡˚
np_baseball = np.array(baseball)
np_baseball  # 1

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [17]:
np_weight = np_baseball[:, 1]
np_weight  # 2

array([ 78.4, 102.7,  98.5,  75.2])

In [18]:
np_baseball = np_baseball * [0.01, 1000]
np_baseball  # 3

array([[1.800e+00, 7.840e+04],
       [2.150e+00, 1.027e+05],
       [2.100e+00, 9.850e+04],
       [1.880e+00, 7.520e+04]])

In [19]:
np.set_printoptions(suppress=True)  # отключаем экспоненциальную запись

In [20]:
np_baseball

array([[     1.8 ,  78400.  ],
       [     2.15, 102700.  ],
       [     2.1 ,  98500.  ],
       [     1.88,  75200.  ]])

In [21]:
print(np.mean(np_baseball[:, 1]))  # 4
print(np.median(np_baseball[:, 0]))

88700.0
1.9900000000000002


In [22]:
np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]  # 5

0.9586573808397336